export const CREATED_SESSION = 'CREATED_SESSION';
export const LEFT_SESSION = 'LEFT_SESSION';
export const JOINED_SESSION = 'JOINED_SESSION';
export const NEW_PARTICIPANT = 'NEW_PARTICIPANT';
export const NO_SUCH_SESSION = 'NO_SUCH_SESSION';
export const PARTICIPANT_LEFT = 'PARTICIPANT_LEFT';
export const RESPONSE_ADDED = 'RESPONSE_ADDED';
